# Generated by Django 4.0.2 on 2022-02-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tutorial',
            table='tutorial',
        ),
    ]
